JOB_ROLES = {
    "backend_dev": {
        "title": "Junior Backend Developer",
        "level": "Junior",
        "description": "Focuses on building scalable server-side logic, API design, and database management.",
        "skills": [
            {"name": "Python", "level": "Advanced"},
            {"name": "Flask", "level": "Advanced"},
            {"name": "SQLAlchemy", "level": "Advanced"},
            {"name": "RESTful APIs", "level": "Advanced"},
            {"name": "PostgreSQL", "level": "Intermediate"},
            {"name": "MySQL", "level": "Intermediate"},
            {"name": "Redis", "level": "Intermediate"},
            {"name": "Docker", "level": "Intermediate"},
            {"name": "Git", "level": "Advanced"},
            {"name": "JWT Authentication", "level": "Advanced"},
            {"name": "OAuth2", "level": "Intermediate"},
            {"name": "Unit Testing", "level": "Intermediate"},
            {"name": "Microservices", "level": "Beginner"},
            {"name": "Celery", "level": "Intermediate"},
            {"name": "Nginx", "level": "Beginner"},
            {"name": "AWS S3", "level": "Intermediate"},
            {"name": "CI/CD Pipelines", "level": "Intermediate"},
            {"name": "OpenAI API", "level": "Intermediate"},
            {"name": "Pydantic", "level": "Advanced"},
            {"name": "Swagger/OpenAPI", "level": "Advanced"},
            {"name": "Data Structures", "level": "Advanced"},
            {"name": "Algorithm Design", "level": "Intermediate"},
            {"name": "System Design Basics", "level": "Beginner"},
            {"name": "Problem Solving", "level": "Advanced"},
            {"name": "Communication", "level": "Intermediate"}
        ]
    },

    "ai_engineer": {
        "title": "AI & Computer Vision Engineer",
        "level": "Junior",
        "description": "Specializes in AI models, computer vision, and ML pipelines.",
        "skills": [
            {"name": "Python", "level": "Advanced"},
            {"name": "PyTorch", "level": "Intermediate"},
            {"name": "TensorFlow", "level": "Intermediate"},
            {"name": "OpenCV", "level": "Advanced"},
            {"name": "MediaPipe", "level": "Advanced"},
            {"name": "NumPy", "level": "Advanced"},
            {"name": "Pandas", "level": "Advanced"},
            {"name": "Scikit-Learn", "level": "Advanced"},
            {"name": "Hugging Face Transformers", "level": "Intermediate"},
            {"name": "CNNs", "level": "Advanced"},
            {"name": "NLP", "level": "Intermediate"},
            {"name": "Deep Learning", "level": "Advanced"},
            {"name": "Model Optimization", "level": "Intermediate"},
            {"name": "ONNX", "level": "Intermediate"},
            {"name": "Object Detection", "level": "Advanced"},
            {"name": "Emotion Recognition", "level": "Advanced"},
            {"name": "Signal Processing", "level": "Intermediate"},
            {"name": "Vector Databases", "level": "Intermediate"},
            {"name": "MLOps Basics", "level": "Beginner"},
            {"name": "Mathematics for ML", "level": "Advanced"},
            {"name": "Git", "level": "Advanced"},
            {"name": "Linux/Bash", "level": "Intermediate"},
            {"name": "Data Annotation", "level": "Intermediate"},
            {"name": "Research Skills", "level": "Intermediate"},
            {"name": "Critical Thinking", "level": "Advanced"}
        ]
    },

    "flutter_dev": {
        "title": "Junior Mobile Developer (Flutter)",
        "level": "Junior",
        "description": "Builds cross-platform mobile apps with Flutter and Dart.",
        "skills": [
            {"name": "Dart", "level": "Advanced"},
            {"name": "Flutter SDK", "level": "Advanced"},
            {"name": "Widget Lifecycle", "level": "Advanced"},
            {"name": "Provider", "level": "Advanced"},
            {"name": "Riverpod", "level": "Intermediate"},
            {"name": "BLoC Pattern", "level": "Intermediate"},
            {"name": "Firebase", "level": "Advanced"},
            {"name": "REST API Integration", "level": "Advanced"},
            {"name": "JSON Serialization", "level": "Advanced"},
            {"name": "SQLite", "level": "Intermediate"},
            {"name": "UI/UX Principles", "level": "Intermediate"},
            {"name": "Animations", "level": "Intermediate"},
            {"name": "Responsive Design", "level": "Advanced"},
            {"name": "State Management", "level": "Advanced"},
            {"name": "Clean Architecture", "level": "Intermediate"},
            {"name": "Dependency Injection", "level": "Intermediate"},
            {"name": "Push Notifications", "level": "Intermediate"},
            {"name": "Git", "level": "Advanced"},
            {"name": "App Deployment", "level": "Beginner"},
            {"name": "Performance Optimization", "level": "Intermediate"},
            {"name": "Widget Testing", "level": "Intermediate"},
            {"name": "Unit Testing", "level": "Intermediate"},
            {"name": "Debugging", "level": "Advanced"},
            {"name": "Problem Solving", "level": "Advanced"},
            {"name": "Collaboration", "level": "Advanced"}
        ]
    },

    "frontend_dev": {
        "title": "Junior Frontend Developer (React)",
        "level": "Junior",
        "description": "Builds modern web interfaces using React and frontend tools.",
        "skills": [
            {"name": "JavaScript", "level": "Advanced"},
            {"name": "TypeScript", "level": "Intermediate"},
            {"name": "React.js", "level": "Advanced"},
            {"name": "HTML5", "level": "Advanced"},
            {"name": "CSS3", "level": "Advanced"},
            {"name": "SCSS", "level": "Intermediate"},
            {"name": "Tailwind CSS", "level": "Advanced"},
            {"name": "Redux Toolkit", "level": "Intermediate"},
            {"name": "React Query", "level": "Intermediate"},
            {"name": "Next.js", "level": "Intermediate"},
            {"name": "Responsive Design", "level": "Advanced"},
            {"name": "DOM Manipulation", "level": "Advanced"},
            {"name": "Browser APIs", "level": "Intermediate"},
            {"name": "Web Performance", "level": "Intermediate"},
            {"name": "Accessibility (WCAG)", "level": "Intermediate"},
            {"name": "Webpack", "level": "Intermediate"},
            {"name": "Vite", "level": "Intermediate"},
            {"name": "Git", "level": "Advanced"},
            {"name": "NPM/Yarn", "level": "Advanced"},
            {"name": "Jest", "level": "Intermediate"},
            {"name": "React Testing Library", "level": "Intermediate"},
            {"name": "Axios", "level": "Advanced"},
            {"name": "State Management", "level": "Advanced"},
            {"name": "Cross-Browser Compatibility", "level": "Advanced"},
            {"name": "Team Communication", "level": "Advanced"}
        ]
    }
}